quarkus.application.name=vending-machine-service
quarkus.http.port=9987

quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/vendingmachineservice
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

teaql.ensureTable=true
teaql.contextClass=com.doublechaintech.vendingmachineservice.CustomUserContext