spring.application.name=vending-machine-service
server.port=9987
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
teaql.ensureTable=true
teaql.contextClass=com.example.vendingmachineservice.CustomUserContext

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/vendingmachineservice
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.port=6379
plc.deploy.url=
card.service.url=
aliyun.sms.ak=
aliyun.sms.sk=