spring.application.name=fifa-world-cup-2026-service
server.port=9987
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
teaql.ensureTable=true
teaql.contextClass=com.example.fifaworldcupservice.CustomUserContext

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:fifaworldcupservice.db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.port=6379
plc.deploy.url=
card.service.url=
aliyun.sms.ak=
aliyun.sms.sk=