micronaut.application.name=vending-machine-service
micronaut.server.port=9987

datasources.default.driverClassName=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/vendingmachineservice
datasources.default.username=postgres
datasources.default.password=postgres

teaql.ensureTable=true
teaql.contextClass=com.example.vendingmachineservice.CustomUserContext